baseURL = "https://couldbethis.github.io/CouldLook/"
languageCode = 'en-us'
title = "CouldLook CL (CL)"
theme = "CouldLook-zen"
# theme = "ananke"

publishDir = "docs"
logo = false

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10
# googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[author]
	author = "CouldBeThis"
	url = "https://github.com/CouldBeThis"
# avatar = ""

[taxonomies]
	category = "categories"
	tag = "tags"

[params]
  cookieConsent = false       # Show cookie consent form, default false.
  # contact = "info@example.org"
  # copyright = "This site is licensed under a (https =//creativecommons.org/licenses/by-sa/4.0/)." [Creative Commons Attribution-ShareAlike 4.0 International License]
  dateformat = "January 2, 2006"    # default to "2 January, 2006"
  description = ""           # Set site description, used in meta tags and JSON-LD
  favicon = ""               # Relative path to favicon in json feed, no leading slash.
  feedlinks = true           # Show feed links in the footer.
  footer = "--- could be this ---"
  icon = ""                  # Relative path to icon in json feed and JSON-LD, no leading slash.
  image = ""                 # Relative path to site image in JSON-LD, no leading slash.
  imageMaxWidth = ""         # Max width for images added via figure shortcode.
  github = "CouldBeThis"
  jquery = true              # Add jQuery
  languageDir = ""           # Set ltr or rtl, defaults to ltr.
  logo = false               # Turn off the logo.
  # logoPath =                 # Relative path to site logo, defaults to "images/logo.png", no leading slash.
  # mainSections              # The sections you want to have listed on the front page.
  #   - "section1"            # Default to the section with most content if not set.
  #   - "section2"            # Set to empty if no section should be listed.
  microUsername = ""         # Your micro.blog username.
  mobileMenu = true          # Turn on a mobile menu on small screens.
  piwikTrackerUrl = ""       # Matamo url, schemaless and no slash on end (example.org/matamo).
  plausibleSiteID = ""       # Plausible site id/domain.
  plausibleTrackerURL = ""   # Plausible url, schemaless and no slash on end. Optional, defaults to "plausible.io/…"
  poweredby = true           # Show powered by hugo in footer
  privacyPolicyUrl = ""      # If set will add link to cookie consent form.

  # realfavicongenerator =     # If full set of favicons, site manifest etc. exists, default false.
  relatedposts = true        # Show related posts under a "See also" section, default false.
  searchLimit = 20           # Max number of search hits, default 20.
  sidebar = true             # Show a sidebar to the right
  submitted = false           # Show author and date information for a post.
  # themeColor =  "#333"             # Hex color value, used in meta tags, default "#ffffff".
  # gitlab = ""
 #  mastodon = ""
 #  stackoverflow = ""
 #  rss = ""
  # twitter = "https://twitter.com/GoHugoIO"
  # instagram = ""

[outputFormats.SearchIndex]
mediaType = "application/json"
baseName = "searchindex"
isPlainText = true
notAlternative = true

# [outputs]
# 	home = [ "HTML", "RSS", "JSON", "SearchIndex" ]
# 	section = [ "HTML", "RSS", "JSON" ]

enableEmoji =  "true"
enableGitInfo =  "enableGitInfo "


# [markup.goldmark]
# 	[markup.goldmark.extensions]
# 		definitionList = true
# 		footnote = true
# 		linkify = true
# 		strikethrough = true
# 		table = true
# 		taskList = true
# 		typographer = true
#
# 	[markup.goldmark.parser]
# 		autoHeadingID = true
# 		autoHeadingIDType = "github"
# 		[markup.goldmark.parser.attribute]
# 			block = false
# 			title = true
#
# 	[markup.goldmark.renderer]
# 		hardWraps = false
# 		unsafe = false
# 		xhtml = false
#
# 	[markup.highlight]
# 		codeFences = true
# 		guessSyntax = true
# 		style = "monokailight"
# 			# available styles: https://xyproto.github.io/splash/docs/all.html
# 		hl_lines = 2
#
# 	[markup.tableOfContents]
# 		endLevel = 3
# 		ordered = true
# 		startLevel = 2
#
# 	[markup.asciidocExt]
# 		backend = 'html5'
# 		extensions = ["asciidoctor-bibtex"]
# 			# Possible extensions are asciidoctor-html5s, asciidoctor-bibtex, asciidoctor-diagram, asciidoctor-interdoc-reftext, asciidoctor-katex, asciidoctor-latex, asciidoctor-mathematical, asciidoctor-question, asciidoctor-rouge.
# 		failureLevel = 'fatal'
# 		noHeaderOrFooter = true
# 		preserveTOC = true
# 		safeMode = 'unsafe'
# 		sectionNumbers = false
# 		trace = false
# 		verbose = false
# 		workingFolderCurrent = false
# 		[markup.asciidocExt.attributes]














